name: Publish Video

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Call Publish API
        run: curl https://launch1-production-36e4.up.railway.app/api/youtube/publish